# Generated by Django 2.2 on 2020-07-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuarioqueja', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('tema', models.CharField(choices=[('f1', 'imcumplimiento'), ('f2', 'anuncio ficticio')], max_length=40)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='Productos.producto')),
            ],
        ),
    ]
